# 1 Write a program that uses a while loop (not a for loop) to read through a string and print the characters of the string one-by-one on separate lines.

In [1]:
str = input("Enter a string: ")
i = 0
while(i < len(str)):
    print("{}\n".format(str[i]))
    i+=1

Enter a string: dark
d

a

r

k



# 2 Modify the program above to print out every second character of the string.

In [12]:
str = input("Enter a string: ")
i = 0
while(i < len(str)):
    if (i+1) % 2 == 0:
        print("{}\n".format(str[i]))
    i+=1

Enter a string: half
a

f



# 3. Write a program that asks the user to enter a password. If the user enters the right password, the program should tell them they are logged in to the system. Otherwise, the program should ask them to reenter the password. The user should only get five tries to enter the password, after which point the program should tell them that they are kicked off of the system.

In [3]:
password = "ere1234"
for x in range(7):
    if x == 0:
        str = input("Enter a password: ")
    else:
        str = input("Re-enter your password: ")
    if str == password:
        print("You are logged in")
        break
    else:
        if 5 - x >= 0:
            print("You have {} tries left".format(5-x))
if x == 6:
    print("You have been kicked out of the system")

Enter a password: wer1234
You have 5 tries left
Re-enter your password: e4rtg
You have 4 tries left
Re-enter your password: ere1234
You are logged in


# 4 Recall that, given a string s , s.index( ' x ' ) returns the index of the first x in s and an error if there is no x. (a) Write a program that asks the user for a string and a letter. Using a while loop, the program should print the index of the first occurrence of that letter and a message if the string does not contain the letter.

In [4]:
def main():
    i = 0
    p = 2
    s = input ('Enter a string ')
    l = input ('Enter a letter ')
    s = s.lower()
    l = l.lower()
    while p != 0:
        if l in s:
            print ('Index is ',s.index(l)+1)
            p = 1
            break
        p = 0
    if p == 0:
        print (l, ' is not found')
main()

Enter a string water
Enter a letter t
Index is  3


# 4 (b) Write the above program using a for/break loop instead of a while loop.

In [5]:
def main():
    i = 1
    p = 1
    s = input ('Enter a string ')
    l = input ('Enter a letter ')
    s = s.lower()
    l = l.lower()
    for ch in s:
        if ch == l:
            print ('Index is ',i)
            p = 0
            break
        i+=1
    if p == 1:
        print (l, ' is not found')
main()

Enter a string party
Enter a letter y
Index is  5


# 5.The GCD (greatest common divisor) of two numbers is the largest number that both are di- visible by. For instance, gcd (18, 42) is 6 because the largest number that both 18 and 42 are divisible by is 6. Write a program that asks the user for two numbers and computes their gcd. Shown below is a way to compute the GCD, called Euclid’s Algorithm.
• First compute the remainder of dividing the larger number by the smaller number

• Next, replace the larger number with the smaller number and the smaller number with the remainder.

• Repeat this process until the smaller number is 0. The GCD is the last value of the larger number.

In [6]:
def main():
    a = input('Enter a number ')
    b = input ('Enter another number ')
    if a > b :
        (lar,sml) = (a,b)
    else:
        (lar,sml) = (b,a)
    while sml != 0:
        (lar,sml) = (sml,int(lar) % int(sml))
    print ('GCD is: ',lar)
main()

Enter a number 43
Enter another number 45
GCD is:  1


# 6.A 4000-year old method to compute the square root of 5 is as follows: Start with an initial guess, say 1. Then compute¶
(1 + 5/1 )/2 = 3

Next, take that 3 and replace the 1’s in the previous formula with 3’s . This gives

(3 + 5/3 )/2 = 7/3 = 2.33

Next replace the 3 in the previous formula with 7/3 . This gives

(7/3 + 5/(7/3) )/2 = 47/22 = 2.24

If you keep doing this process of computing the formula, getting a result, and plugging it back in, the values will eventually get closer and closer to 5 . This method works for numbers other than 5. Write a program that asks the user for a number and uses this method to estimate the square root of the number correct to within 10^( −10) . The estimate will be correct to within 10^( −10) when the absolute value of the difference between consecutive values is less than 10^(−10) .

In [8]:
def main():
    num = input('Enter a number ')
    num = float(num)
    error = 10.00
    error1 = 10 ** -10
    ig = 1
    while error >= error1:
        result = (ig + (float(num)/float(ig)))
        result1 = float(result)/2
        error = (num - result1)
        ig = result
    print ('Square root is: ' , result1)
main()

Enter a number 6
Square root is:  6.092153522483485


# 7.Write a program that starts with an 5 × 5 list of zeroes and randomly changes exactly ten of those zeroes to ones.¶

In [11]:
import random
myList = []
randomPosition = []
for i in range(25):
    myList.append(0)

for i in range(10):
    x = random.randrange(1, 25)
    while randomPosition.count(x) != 0:
        x = random.randrange(1, 25)
    randomPosition.append(x)
    myList[x] = 1
k = 0
for i in range (5):
    for j in range(5):
        if i+j == randomPosition[k]:
            print(myList[k], end=" ")
            k+=1
            continue
        print(myList[i+j], end=" ")
    print()

0 1 0 1 0 
1 0 1 0 0 
0 1 0 0 0 
1 0 0 0 0 
0 0 0 0 0 


# 8.Write a program in which you have a list that contains seven integers that can be 0 or 1. Find the first nonzero entry in the list and change it to a 1. If there are no nonzero entries, print a message saying so.

In [13]:
import random
def main():
    list = []
    i = 0
    n = 0
    for i in range (0,7):
        x = random.randint(0,10)
        list.append(x)
    print (list)
    for i in range (0,7):
        if list[i] > 0:
            print ('First nonzero element is ',list[i], ' in index ',i+1)
            list[i] = 1
            n = 1
            print ('After replace the list ',list)
            break
    if n == 0:
        print ('There is no non zero entries')
main()

[10, 9, 0, 8, 4, 6, 4]
First nonzero element is  10  in index  1
After replace the list  [1, 9, 0, 8, 4, 6, 4]


# 9.Write a program to play the following simple game. The player starts with 100.𝑂𝑛𝑒𝑎𝑐ℎ𝑡𝑢𝑟𝑛𝑎𝑐𝑜𝑖𝑛𝑖𝑠𝑓𝑙𝑖𝑝𝑝𝑒𝑑𝑎𝑛𝑑𝑡ℎ𝑒𝑝𝑙𝑎𝑦𝑒𝑟ℎ𝑎𝑠𝑡𝑜𝑔𝑢𝑒𝑠𝑠ℎ𝑒𝑎𝑑𝑠𝑜𝑟𝑡𝑎𝑖𝑙𝑠.𝑇ℎ𝑒𝑝𝑙𝑎𝑦𝑒𝑟𝑤𝑖𝑛𝑠 9 for each correct guess and loses 10𝑓𝑜𝑟𝑒𝑎𝑐ℎ𝑖𝑛𝑐𝑜𝑟𝑟𝑒𝑐𝑡𝑔𝑢𝑒𝑠𝑠.𝑇ℎ𝑒𝑔𝑎𝑚𝑒𝑒𝑛𝑑𝑠𝑒𝑖𝑡ℎ𝑒𝑟𝑤ℎ𝑒𝑛𝑡ℎ𝑒𝑝𝑙𝑎𝑦𝑒𝑟𝑟𝑢𝑛𝑠𝑜𝑢𝑡𝑜𝑓𝑚𝑜𝑛𝑒𝑦𝑜𝑟𝑔𝑒𝑡𝑠𝑡𝑜 200.¶

In [15]:
balance=25  #100

def Guess(ans,my_balance):
    import random
    z=random.randint(0,1)
    if ans==z:
        my_balance=my_balance+9
        print('Right Guess!!! New Balance',my_balance)
    else:
        my_balance=my_balance-10
        print('Wrong Guess... New Balance',my_balance)
    return my_balance

print('Starts with $25 and wins when $50')
while balance>0 and balance<50:  #balance<200
    s=input('write "H" for head or "T" for tail ')
    if s=='H':
        check=Guess(0,balance)  # 0 for head
    elif s=='T':
        check=Guess(1,balance)  # 1 for tail
    balance=check

if balance>=50:          #200
    print('Congrats!!!')
else:
    print('Better Luck Next time...')

Starts with $25 and wins when $50
write "H" for head or "T" for tail H
Wrong Guess... New Balance 15
write "H" for head or "T" for tail T
Wrong Guess... New Balance 5
write "H" for head or "T" for tail T
Wrong Guess... New Balance -5
Better Luck Next time...


# 10.Randomly generate a 6 × 6 list that has exactly 12 ones placed in random locations in the list. The rest of the entries should be zeroes.¶

In [18]:
import numpy as np
import random
def main():
    i = 0
    j = 0
    count = 0
    list = np.random.choice([0, 1], p=[0.7, 0.3], size=(6, 6))
    while count != -1:
        list = np.random.choice([0, 1], p=[0.7, 0.3], size=(6, 6))
        count = 0
        for i in range(0,6):
            for j in range (0,6):
                if list [i][j] == 1:
                    count += 1
        if count == 12:
            break
    print (list)
main()

[[1 0 0 1 1 0]
 [0 0 1 1 0 0]
 [0 0 1 1 1 1]
 [0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]]


# 10.Randomly generate a 9 × 9 list where the entries are integers between 1 and 9 with no repeat entries in any row or in any column.

In [22]:
import random
positions = []
for x in range(9):
    for y in range(9):
        f = random.randrange(9)+1
        while positions.count(f)!=0:
            f = random.randrange(9)+1
        positions.append(f)
        print(f, end=" ")
    positions.clear()
    print()

8 5 2 7 9 6 1 3 4 
2 8 6 1 4 3 5 7 9 
5 6 9 2 8 4 1 3 7 
1 6 2 5 3 4 9 7 8 
5 6 4 8 3 1 7 2 9 
9 3 2 6 8 7 4 5 1 
8 6 4 3 1 9 7 5 2 
6 9 1 4 3 2 7 8 5 
2 4 3 1 7 9 8 5 6 


# 1.Write a program that repeatedly asks the user to enter product names and prices. Store all of these in a dictionary whose keys are the product names and whose values are the prices. When the user is done entering products and prices, allow them to repeatedly enter a product name and print the corresponding price or a message if the product is not in the dictionary

In [24]:
ch="Y"
dic={}

while ch=='Y':
    p_n=input('Enter Product Name: ')
    p_pr=input('Enter Product Prize: ')
    dic[p_n]=p_pr
    ch=input('Press "Y" to add more OR "N" to finish: ')

ch="Y"
while ch=="Y":
    a=input('Enter Product Name: ')
    if a in dic:
        print('Price of',a,'is:',dic[a])
    else:
        print(a,'is not in the Dictionary')
    ch=input('Press "Y" to search again OR "N" to finish: ')

Enter Product Name: Cake
Enter Product Prize: 345
Press "Y" to add more OR "N" to finish: Y
Enter Product Name: soda
Enter Product Prize: 35
Press "Y" to add more OR "N" to finish: Y
Enter Product Name: WATER
Enter Product Prize: 45
Press "Y" to add more OR "N" to finish: N
Enter Product Name: coke
coke is not in the Dictionary
Press "Y" to search again OR "N" to finish: N


# 2.Using the dictionary created in the previous problem, allow the user to enter a dollar amount and print out all the products whose price is less than that amount.¶

In [25]:
ch="Y"
dic={}

while ch=='Y':
    p_n=input('Enter Product Name: ')
    p_pr=input('Enter Product Prize: ')
    dic[p_n]=p_pr
    ch=input('Press "Y" to add more OR "N" to finish: ')

n=input('Enter a Doller amount: ')
n=int(n)  #string to int
c=0  #to check if required product exists

for p in dic:
    if int(dic[p])<n:  #type casting as the dictionary value is string
        print(p,':',dic[p])
        c=c+1
if c==0:
    print('No product exists in the Dictionary Price less than',n)

Enter Product Name: cola
Enter Product Prize: 34
Press "Y" to add more OR "N" to finish: N
Enter a Doller amount: 34
No product exists in the Dictionary Price less than 34


# 3.Write a program that uses a dictionary that contains ten user names and passwords. The program should ask the user to enter their username and password. If the username is not in the dictionary, the program should indicate that the person is not a valid user of the system. If the username is in the dictionary, but the user does not enter the right password, the program should say that the password is invalid. If the password is correct, then the program should tell the user that they are now logged in to the system.

In [26]:
dic={'Asha':1234560, 'Mir': 13156910, 'Ovi': 11420119113, 
     'hena': 811414919, 'Hridy': 818941525, 'Rafa': 291821, 'Sazid': 315896, 
     'Ira': 1821139, 'Sid': 17201407, 'Proma': 201514}

u_n=input('Enter User Name: ')
p_w=input('Enter Password: ')
p_w=int(p_w)
               # string comparison isn't working.   have to type cast in int
if u_n in dic:
    if int(dic[u_n])==p_w:
        print('Login Successfull !!!')
    else:
        print('Invalid Password...')
else:
    print('You are Not a valid User...')

Enter User Name: Asha
Enter Password: 12345
Invalid Password...


# 4.Using the card dictionary from earlier in this chapter, create a simple card game that deals two players three cards each. The player with the highest card wins. If there is a tie, then compare the second highest card and, if necessary, the third highest. If all three cards have the same value, then the game is a draw.

In [34]:
import random
import operator
deck = [{ ' value ' :i, ' suit ' :c}
for c in [ ' spades ' , ' clubs ' , ' hearts ' , ' diamonds ' ]
for i in range(2,15)]
deck1 = {}
deck2 = {}
arr1 = [None]*3
arr2 = [None]*3

random.shuffle(deck)
#for player one
print("Player One:")
for i in range(0,3):
    deck1 = deck[i]
    print(deck[i])
    x = max(deck1)
    arr1[i] = deck1[x]

print(arr1)    
print("\nPlayer Two:")
#for player two

random.shuffle(deck)
for i in range(0,3):
    deck2 = deck[i]
    print(deck[i])
    y = max(deck2)
    arr2[i] = deck2[y]
    
print(arr2)

firstMax = max(arr1)
seccondMax = max(arr2)
print("\nHighest Value of Player One ",firstMax)
print("\nHigest Value of Player Two: ",seccondMax)
if(firstMax==seccondMax):
    print("\nGame Tie\n")
elif(firstMax>seccondMax):
    print("\nPlayer One won\n")
elif(seccondMax>firstMax):
    print("\nPlayer Two Won\n")

Player One:
{' value ': 14, ' suit ': ' spades '}
{' value ': 6, ' suit ': ' spades '}
{' value ': 3, ' suit ': ' hearts '}
[14, 6, 3]

Player Two:
{' value ': 13, ' suit ': ' diamonds '}
{' value ': 7, ' suit ': ' clubs '}
{' value ': 3, ' suit ': ' clubs '}
[13, 7, 3]

Highest Value of Player One  14

Higest Value of Player Two:  13

Player One won



# 5.Using the card dictionary from earlier in the chapter, deal out three cards. Determine the following: (a) If the three cards form a flush (all of the same suit) (b) If there is a three-of-a-kind (all of the same value) (c) If there is a pair, but not three-of-a-kind (d) If the three cards form a straight (all in a row, like (2, 3, 4) or (10, Jack, Queen))

In [32]:
deck = [{ 'value': i, 'suit': c}
for c in [ 'spades' , 'clubs', 'hearts', 'diamonds']
for i in range(2,15)]

random.shuffle(deck)   # to shuffle the cards
p_1=[0]*3              # value '2' of clubs
p_2=['s']*3            # suit 2 of "clubs"

check=0
print('Cards: ')
while check<3:
    print(deck[check]['suit'],':',deck[check]['value'])
    p_1[check]=int(deck[check]['value'])
    p_2[check]=deck[check]['suit']
    check=check+1


p_1=sorted(p_1, reverse=True)  # 10, 9, 7
    
if p_1[0]==p_1[1]==p_1[2]:
    print('Three of A Kind')
elif p_2[0]==p_2[1]==p_2[2]:
    if p_1[0]==p_1[1]+1 and p_1[0]==p_1[2]+2:
        print('Straight Flush')
    else:
        print('Flush')
elif p_1[0]==p_1[1] or p_1[0]==p_1[2] or p_1[2]==p_1[1]:
    print('Pair')
elif p_1[0]==p_1[1]+1 and p_1[0]==p_1[2]+2:
        print('Straight')
else:
    print('High Card :',p_1[0])

Cards: 
spades : 6
spades : 14
diamonds : 13
High Card : 14


# 6.Below are the notes used in music: C C# D D# E F F# G G# A A# B The notes for the C major chord are C, E, G. A mathematical way to get this is that E is 4 steps past C and G is 7 steps past C. This works for any base. For example, the notes for D major are D, F#, A. We can represent the major chord steps as a list with two elements: [4,7] . The corresponding lists for some other chord types are shown below: Minor [3,7]
Augmented fifth [4,8]

Minor fifth [4,6]

Major sixth [4,7,9]

Minor sixth [3,7,9]

Dominant seventh [4,7,10]

Minor seventh [3,7,10]

Major seventh [4,7,11]

Diminished seventh [3,6,10]

Write a program that asks the user for the key and the chord type and prints out the notes of the chord. Use a dictionary whose keys are the (musical) keys and whose values are the lists of steps.

In [31]:
my_note=['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']

print('Cord types are : Minor, Augmented fifth, Minor fifth, Major sixth, Minor sixth\n \t\tDominant seventh, Minor seventh, Major seventh, Diminished seventh')
key=input('Enter Key: ')
cord_type=input('Enter Cord Type: ')

i=0
while i<12:
    if my_note[i]==key:
        break
    i=i+1

if cord_type=='Minor':
    print(my_note[i],my_note[i+3],my_note[(i+7)%11])
elif cord_type=='Augmented fifth':
    print(my_note[i],my_note[i+4],my_note[(i+8)%11])
elif cord_type=='Minor fifth':
    print(my_note[i],my_note[i+4],my_note[(i+6)%11])
elif cord_type=='Major sixth':
    print(my_note[i],my_note[i+4],my_note[(i+7)%11], my_note[(i+9)%11])
elif cord_type=='Dominant seventh':
    print(my_note[i],my_note[i+4],my_note[(i+7)%11], my_note[(i+10)%11])
elif cord_type=='Minor seventh':
    print(my_note[i],my_note[i+3],my_note[(i+7)%11], my_note[(i+10)%11])
elif cord_type=='Major seventh':
    print(my_note[i],my_note[i+4],my_note[(i+7)%11],my_note[(i+11)%11])
elif cord_type=='Diminished seventh':
    print(my_note[i],my_note[i+3],my_note[(i+6)%11], my_note[(i+10)%11])
elif cord_type=='Minor sixth':
    print(my_note[i],my_note[i+3],my_note[(i+7)%11], my_note[(i+9)%11])

Cord types are : Minor, Augmented fifth, Minor fifth, Major sixth, Minor sixth
 		Dominant seventh, Minor seventh, Major seventh, Diminished seventh
Enter Key: C
Enter Cord Type: C G E


# 7.Suppose you are given the following list of strings: L = [ ' aabaabac ' , ' cabaabca ' , ' aaabbcba ' , ' aabacbab ' , ' acababba ' ]
Patterns like this show up in many places, including DNA sequencing. The user has a string of their own with only some letters filled in and the rest as asterisks. An example is aa** . The user would like to know which of the strings in the list fit with their pattern. In the example just given, the matching strings are the first and fourth. One way to solve this problem is to create a dictionary whose keys are the indices in the user’s string of the non-asterisk characters and whose values are those characters. Write a program implementing this approach (or some other approach) to find the strings that match a user-entered string.

In [36]:
L = [ 'aabaabac' , 'cabaabca' , 'aaabbcba' , 'aabacbab' , 'acababba' ] 

s=input("Enter string with one * :")

i=0
check=0
while i<5:
    check=0
    m=0
    if s[m]==L[i][m]:
        check=1
        m=m+1
        while m<len(s)-1 and check==1:
            if s[m]!=L[i][m]:
                check=0
        m=m+1
    if check==1:
        print(L[i])
    i=i+1

if check==0:
    print('No Match')

Enter string with one * :era*
No Match


# 8.Dictionaries provide a convenient way to store structured data. Here is an example dictionary: d=[{ ' name ' : ' Todd ' , ' phone ' : ' 555-1414 ' , ' email ' : ' todd@mail.net ' }, { ' name ' : ' Helga ' , ' phone ' : ' 555-1618 ' , ' email ' : ' helga@mail.net ' }, { ' name ' : ' Princess ' , ' phone ' : ' 555-3141 ' , ' email ' : '' }, { ' name ' : ' LJ ' , ' phone ' : ' 555-2718 ' , ' email ' : ' lj@mail.net ' }]
Write a program that reads through any dictionary like this and prints the following:

(a) All the users whose phone number ends in an 8

(b) All the users that don’t have an email address listed

In [41]:
d=[{ ' name ' : ' Todd ' , ' phone ' : ' 555-1414 ' , ' email ' : ' todd@mail.net ' }, 
   { ' name ' : ' Helga ' , ' phone ' : ' 555-1618 ' , ' email ' : ' helga@mail.net ' }, 
   { ' name ' : ' Princess ' , ' phone ' : ' 555-3141 ' , ' email ' : '' }, 
   { ' name ' : ' LJ ' , ' phone ' : ' 555-2718 ' , ' email ' : ' lj@mail.net ' }]
#print(d[2][' email '])
#a=''
#print(len(a))

print('All the users whose phone number ends in an 8')
i=0
for a in d:
    n=d[i][' phone ']
    if n[-2]=='8':
        print(d[i])
    i=i+1

print('\nAll the users that don’t have an email address listed')
i=0
for a in d:
    n=d[i][' email ']
    if len(n)==0:
        print(d[i])
    i=i+1

All the users whose phone number ends in an 8
{' name ': ' Helga ', ' phone ': ' 555-1618 ', ' email ': ' helga@mail.net '}
{' name ': ' LJ ', ' phone ': ' 555-2718 ', ' email ': ' lj@mail.net '}

All the users that don’t have an email address listed
{' name ': ' Princess ', ' phone ': ' 555-3141 ', ' email ': ''}
